name: Build and deploy Node.js app to Google Cloud App Engine - kschat

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'
      - uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
